"""empty message

Revision ID: 5c58853b277d
Revises: b495c0906c64
Create Date: 2023-04-18 16:52:43.047699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c58853b277d'
down_revision = 'b495c0906c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))


    op.execute('UPDATE public."Artist" SET created_time = now() where created_time IS NULL')
    op.execute('UPDATE public."Show" SET created_time = now() where created_time IS NULL')
    op.execute('UPDATE public."Venue" SET created_time = now() where created_time IS NULL')

    op.alter_column('Artist', 'created_time', nullable=False)
    op.alter_column('Show', 'created_time', nullable=False)
    op.alter_column('Venue', 'created_time', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###
